import bcrypt from 'bcrypt';
import { Knex } from 'knex';

const password_hash = bcrypt.hashSync('123456', 8);
const cnpj = '12345678900';
const site = 'https://restaurant.com';
const phone = '(11) 93123-4566';
const tables_amount = 5;
const opening_hour = '19:30:00';
const closing_hour = '23:45:00';
const restaurant_ids = {
  1: '3eb6cc7e-36f2-49af-b675-902cf3a0df36',
  2: '62667f43-2421-4965-b978-d1f02a22f796',
  3: 'a469542a-85ff-4379-932d-d1a7cd3f25e1',
  4: '1b5fe03a-d628-48ea-9bd5-7149e082bf40',
  5: 'ddaa1666-37f8-4003-9e69-708b1d8090b6',
  6: '9d01826e-5870-4631-9995-c438b7094ee7',
  7: 'bcc91d5e-1d51-4b41-9a39-685d0f1c413f',
  8: '3fa9e46c-95f8-4245-aaff-7097a166fd1a',
  9: 'e743589c-6343-417e-8585-9570d47b3f0b',
  10: '35ef3f07-9ce2-4eef-a96c-4bfdf378ee89',
  11: '988a11ee-dbd2-4e1a-b86a-879b8666a9dc',
  12: '1b5c10f3-0ce3-49f5-bf1a-9dab7dad59bd',
};
const culinary_ids = {
  1: '6f89d28e-b7bd-4c06-8d12-8dbd1efe1155',
  2: 'af486eb0-6eaa-4d8c-a028-62ed8c9e73f0',
  3: '92e9459b-dd33-4e65-92aa-bc9bd9e3c1db',
  4: 'eb5a300a-b425-468a-98a6-22250767da9f',
  5: 'd93ea51a-fab7-4234-b48d-087022631801',
  6: '35d2d435-3439-479d-a4dc-53ad0e82b504',
  7: '16a575f1-7ff7-45fe-a261-00cad902fcbd',
  8: '7a214914-f473-45bb-af3f-88d0dcf91850',
  9: '3219af3d-472e-4897-91ea-c5121784224c',
  10: 'bb6bb88a-9ca4-439e-83c7-c5febd2bfbaf',
  11: 'c8360280-7df2-4cf7-8d11-c8a1f3fc0b44',
};

export async function seed(knex: Knex): Promise<void> {
  await knex('restaurants').insert([
    {
      id: restaurant_ids[1],
      name: 'Comida Mineira',
      email: 'comidamineira@gmail.com',
      password_hash,
      cnpj,
      about: `At Our Restaurant we specialize in true Italian cooking. We use the freshest ingredients that reflect authentic Sicilian cuisine with a touch of Northern Italy. Shop our retail section to pair the perfect wine with your meal.`,
      phone,
      site,
      culinary_id: culinary_ids[1],
      tables_amount,
      opening_hour,
      closing_hour,
    },
    {
      id: restaurant_ids[2],
      name: 'Carnes Brasil',
      email: 'carnesbrasil@gmail.com',
      password_hash,
      cnpj: cnpj + 1,
      about: `Housed in a National Historic Building, c.1835, and in business since 1981, Café Vermilionville is a locally-owned, award-winning culinary establishment that serves innovative, upscale creole fare.`,
      phone,
      site,
      culinary_id: culinary_ids[2],
      tables_amount,
      opening_hour,
      closing_hour,
    },
    {
      id: restaurant_ids[3],
      name: 'Esfirra do Gil',
      email: 'rogerio@gmail.com',
      password_hash,
      cnpj: cnpj + 2,
      about: `Our Italian menu features a variety of dishes made from the freshest ingredients to provide our diners with an authentic Italian meal. From pizzas and calzones to fish and filet mignon, we provide something for every taste, craving and budget.`,
      phone,
      site,
      culinary_id: culinary_ids[3],
      tables_amount,
      opening_hour,
      closing_hour,
    },
    {
      id: restaurant_ids[4],
      name: 'Bar do Chico Lopes',
      email: 'chicolopes@gmail.com',
      password_hash,
      cnpj: cnpj + 3,
      about: `Ruth's Chris Steak House in Lafayette, LA serves the finest USDA Prime beef available, broiled at 1,800° and served on 500° plates, so your steak stays hot, juicy and delicious from first bite to last.`,
      phone,
      site,
      culinary_id: culinary_ids[4],
      tables_amount,
      opening_hour,
      closing_hour,
    },
    {
      id: restaurant_ids[5],
      name: 'Padoca do Marcola',
      email: 'padocadomarcola@gmail.com',
      password_hash,
      cnpj: cnpj + 4,
      about: `Be real. Eat good. It"s all about being true to who you are: sharing with friends and family and enjoying each other's company over a good meal. The ingredients are always fresh and that is the cornerstone of our farm to table approach.`,
      phone,
      site,
      culinary_id: culinary_ids[4],
      tables_amount,
      opening_hour,
      closing_hour,
    },
    {
      id: restaurant_ids[6],
      name: 'Hamburgueria Novo Sabor',
      email: 'hamburguerianovosabor@gmail.com',
      password_hash,
      cnpj: cnpj + 5,
      about: `Twin Peaks is an American sports bar and restaurant. The restaurant embodies everything about the classic sports bar. There are high definitions on virtually every wall, ensuring that every guest has a great view of the game.`,
      phone,
      site,
      culinary_id: culinary_ids[5],
      tables_amount,
      opening_hour,
      closing_hour,
    },
    {
      id: restaurant_ids[7],
      name: 'Cantinho do sul',
      email: 'cantinhodosul@gmail.com',
      password_hash,
      cnpj: cnpj + 6,
      about: `Housed in a National Historic Building, c.1835, and in business since 1981, Café Vermilionville is a locally-owned, award-winning culinary establishment that serves innovative, upscale creole fare.`,
      phone,
      site,
      culinary_id: culinary_ids[6],
      tables_amount,
      opening_hour,
      closing_hour,
    },
    {
      id: restaurant_ids[8],
      name: 'Nordeste com você',
      email: 'nordestecomvoce@gmail.com',
      password_hash,
      cnpj: cnpj + 7,
      about: `Our Italian menu features a variety of dishes made from the freshest ingredients to provide our diners with an authentic Italian meal. From pizzas and calzones to fish and filet mignon, we provide something for every taste, craving and budget.`,
      phone,
      site,
      culinary_id: culinary_ids[7],
      tables_amount,
      opening_hour,
      closing_hour,
    },
    {
      id: restaurant_ids[9],
      name: 'Bar do Juca',
      email: 'bardojuca@gmail.com',
      password_hash,
      cnpj: cnpj + 8,
      about: `Ruth's Chris Steak House in Lafayette, LA serves the finest USDA Prime beef available, broiled at 1,800° and served on 500° plates, so your steak stays hot, juicy and delicious from first bite to last.`,
      phone,
      site,
      culinary_id: culinary_ids[8],
      tables_amount,
      opening_hour,
      closing_hour,
    },
    {
      id: restaurant_ids[10],
      name: 'Luffy Picanharia',
      email: 'gangstergastino@gmail.com',
      password_hash,
      cnpj: cnpj + 9,
      about: `Be real. Eat good. It"s all about being true to who you are: sharing with friends and family and enjoying each other's company over a good meal. The ingredients are always fresh and that is the cornerstone of our farm to table approach.`,
      phone,
      site,
      culinary_id: culinary_ids[9],
      tables_amount,
      opening_hour,
      closing_hour,
    },
    {
      id: restaurant_ids[11],
      name: 'Mercadinho do Docs',
      email: 'crissytirocerto@gmail.com',
      password_hash,
      cnpj: cnpj + 10,
      about: `Twin Peaks is an American sports bar and restaurant. The restaurant embodies everything about the classic sports bar. There are high definitions on virtually every wall, ensuring that every guest has a great view of the game.`,
      phone,
      site,
      culinary_id: culinary_ids[10],
      tables_amount,
      opening_hour,
      closing_hour,
    },
    {
      id: restaurant_ids[12],
      name: 'Burger Queen',
      email: 'burgerqueen@gmail.com',
      password_hash,
      cnpj: cnpj + 11,
      about: `Housed in a National Historic Building, c.1835, and in business since 1981, Café Vermilionville is a locally-owned, award-winning culinary establishment that serves innovative, upscale creole fare.`,
      phone,
      site,
      culinary_id: culinary_ids[11],
      tables_amount,
      opening_hour,
      closing_hour,
    },
  ]);
}
