import { Knex } from 'knex';

const site = 'https://restaurant.com';
const phone = '(11) 93123-4566';
const restaurant_ids = {
  1: '3eb6cc7e-36f2-49af-b675-902cf3a0df36',
  2: '62667f43-2421-4965-b978-d1f02a22f796',
  3: 'a469542a-85ff-4379-932d-d1a7cd3f25e1',
  4: '1b5fe03a-d628-48ea-9bd5-7149e082bf40',
  5: 'ddaa1666-37f8-4003-9e69-708b1d8090b6',
  6: '9d01826e-5870-4631-9995-c438b7094ee7',
  7: 'bcc91d5e-1d51-4b41-9a39-685d0f1c413f',
  8: '3fa9e46c-95f8-4245-aaff-7097a166fd1a',
  9: 'e743589c-6343-417e-8585-9570d47b3f0b',
  10: '35ef3f07-9ce2-4eef-a96c-4bfdf378ee89',
  11: '988a11ee-dbd2-4e1a-b86a-879b8666a9dc',
  12: '1b5c10f3-0ce3-49f5-bf1a-9dab7dad59bd',
};

const culinary_ids = {
  1: '58cb901f-b932-42b2-af43-725b73f00f81',
  2: 'ddcf3494-8d60-4045-9503-2299ca72ecfd',
  3: '554e4489-b178-4374-a972-6f861207e09e',
  4: '9905743f-799a-4153-806a-6d9f732163e9',
  5: '1e79f368-159b-4235-8d5d-32d13f7437f7',
  6: 'daaf74f3-392b-4c69-b217-39d41b266ccc',
  7: '7abd6513-aadf-4037-80a6-175fe5187937',
  8: 'a3e76af0-2953-4345-8307-948a1d49d2ba',
  9: '8cf4620f-c764-44da-8689-5af603928262',
  10: 'd3d694a7-7187-4143-8f57-002282b19d02',
  11: '4d31a058-47a6-4b55-94bf-55370407c2be',
};

export async function seed(knex: Knex): Promise<void> {
  await knex('restaurants').insert([
    {
      about: `At Our Restaurant we specialize in true Italian cooking. We use the freshest ingredients that reflect authentic Sicilian cuisine with a touch of Northern Italy. Shop our retail section to pair the perfect wine with your meal.`,
      phone,
      site,
      restaurant_id: restaurant_ids[1],
      culinary_id: culinary_ids[1],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      about: `Housed in a National Historic Building, c.1835, and in business since 1981, Café Vermilionville is a locally-owned, award-winning culinary establishment that serves innovative, upscale creole fare.`,
      phone,
      site,
      restaurant_id: restaurant_ids[2],
      culinary_id: culinary_ids[2],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      about: `Our Italian menu features a variety of dishes made from the freshest ingredients to provide our diners with an authentic Italian meal. From pizzas and calzones to fish and filet mignon, we provide something for every taste, craving and budget.`,
      phone,
      site,
      restaurant_id: restaurant_ids[3],
      culinary_id: culinary_ids[3],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      about: `Ruth's Chris Steak House in Lafayette, LA serves the finest USDA Prime beef available, broiled at 1,800° and served on 500° plates, so your steak stays hot, juicy and delicious from first bite to last.`,
      phone,
      site,
      restaurant_id: restaurant_ids[4],
      culinary_id: culinary_ids[4],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      about: `Be real. Eat good. It"s all about being true to who you are: sharing with friends and family and enjoying each other's company over a good meal. The ingredients are always fresh and that is the cornerstone of our farm to table approach.`,
      phone,
      site,
      restaurant_id: restaurant_ids[5],
      culinary_id: culinary_ids[4],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      about: `Twin Peaks is an American sports bar and restaurant. The restaurant embodies everything about the classic sports bar. There are high definitions on virtually every wall, ensuring that every guest has a great view of the game.`,
      phone,
      site,
      restaurant_id: restaurant_ids[6],
      culinary_id: culinary_ids[5],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      about: `Housed in a National Historic Building, c.1835, and in business since 1981, Café Vermilionville is a locally-owned, award-winning culinary establishment that serves innovative, upscale creole fare.`,
      phone,
      site,
      restaurant_id: restaurant_ids[7],
      culinary_id: culinary_ids[6],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      about: `Our Italian menu features a variety of dishes made from the freshest ingredients to provide our diners with an authentic Italian meal. From pizzas and calzones to fish and filet mignon, we provide something for every taste, craving and budget.`,
      phone,
      site,
      restaurant_id: restaurant_ids[8],
      culinary_id: culinary_ids[7],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      about: `Ruth's Chris Steak House in Lafayette, LA serves the finest USDA Prime beef available, broiled at 1,800° and served on 500° plates, so your steak stays hot, juicy and delicious from first bite to last.`,
      phone,
      site,
      restaurant_id: restaurant_ids[9],
      culinary_id: culinary_ids[8],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      about: `Be real. Eat good. It"s all about being true to who you are: sharing with friends and family and enjoying each other's company over a good meal. The ingredients are always fresh and that is the cornerstone of our farm to table approach.`,
      phone,
      site,
      restaurant_id: restaurant_ids[10],
      culinary_id: culinary_ids[9],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      about: `Twin Peaks is an American sports bar and restaurant. The restaurant embodies everything about the classic sports bar. There are high definitions on virtually every wall, ensuring that every guest has a great view of the game.`,
      phone,
      site,
      restaurant_id: restaurant_ids[11],
      culinary_id: culinary_ids[10],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      about: `Housed in a National Historic Building, c.1835, and in business since 1981, Café Vermilionville is a locally-owned, award-winning culinary establishment that serves innovative, upscale creole fare.`,
      phone,
      site,
      restaurant_id: restaurant_ids[12],
      culinary_id: culinary_ids[11],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ]);
}
